### ISSUE TITLE
Hello World | Night's Blog

### ISSUE THREAD

**Issue by junzkn** [junzkn/junzkn.github.io#3]
https://junzkn.github.io/2018/10/19/hello-world/ 

 Welcome to Hexo! This is your very first post. Check documentation for more info. If you get any problems when using Hexo, you can find the answer in troubleshooting or you can ask me on GitHub. Quick

**Comment by junzkn** [comment]
good

**Comment by junzkn** [comment]
test

**Comment by junzkn** [comment]
测试

**Comment by JULIUSJIANG** [comment]
你好
